seapath-machine-common-qcom: change libvirt preferred version to 11.4.0
Change libvirt preferred version to 11.4.0. This is necessary because
meta-qcom-hwe sets the preferred version to 9.2.0 and the error is fixed
in the newer version of libvirt.

The error:
libvirt.libvirtError: internal error: unknown architecture 'loongarch64'

A discussion about the error:
https://www.linuxquestions.org/questions/slackware-14/virtual-machine-manager-error-4175746069/

Signed-off-by: Florent Mussard <florent.mussard@savoirfairelinux.com>